import { IDish } from "../../models/IDish";

export const FOOD_CATEGORIES = [
  'Entradas',
  'Sopas',
  'Típicos',
  'Parrilla',
  'Pescados',
  'Casuales',
  'Pastas',
  'Infantil',
  'Bebidas',
];

export const DEFAULT_FOODS: Array<IDish> = [
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Porción de gallina gigante, carne de res., carne de cerdo, chuguas, cubios, habas, arvejita, papa sabanera y mazorca, todo cocido en un rico guiso tradicional boyacense, acompañado de arroz y aguacate.',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },
  {
    id: 1,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Entradas',
    stars: 5,
  },

  {
    id: 2,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Lengua en salsa',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Típicos',
    stars: 5,
  },
  {
    id: 3,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Típicos',
    stars: 5,
  },
  {
    id: 4,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Parilla',
    stars: 5,
  },
  {
    id: 5,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30000,
    foodType: 'Pescados',
    stars: 5,
  },
  {
    id: 6,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Bebidas',
    stars: 5,
  },
  {
    id: 7,
    image: 'https://red-onion-restaurant-41dbe.web.app/assets/Breakfast/breakfast1.png',
    name: 'Cocido Boyacense',
    description: 'Delicioso cocido kasndasd asdknad',
    price: 30,
    foodType: 'Bebidas',
    stars: 5,
  },

];